import type { ActionRecordRaw } from "@/types/action";

export const staticActions = [
  {
    id: "menu",
    pId: "",
    actionId: "menu",
    title: "示例菜单",
    type: MenuPageType.MENU,
    sort: 1,
    showInMenu: ShowInMenuType.SHOW,
    url: "page",
    children: [{
      id: "page",
      pId: "menu",
      actionId: "page",
      title: "示例页面",
      type: MenuPageType.PAGE,
      sort: 11,
      showInMenu: ShowInMenuType.SHOW,
      url: "",
      component: "pages/SamplePage.vue",
    }],
  }, {
    id: "settings",
    pId: "",
    actionId: "SysSettings",
    title: "系统管理",
    type: MenuPageType.MENU,
    sort: 9,
    showInMenu: ShowInMenuType.SHOW,
    url: "settings",
    // TODO 完善基本设置页面
    children: [
      {
        id: "form-designer",
        pId: "settings",
        actionId: "formDesigner",
        title: "表单设计器",
        type: MenuPageType.PAGE,
        sort: 2,
        showInMenu: ShowInMenuType.SHOW,
        url: "form",
        component: "form/FormDesigner.vue",
        // }, {
        //     id: "1536652592875048960",
        //     pId: "1536652503813197824",
        //     actionId: "UserMng",
        //     title: "用户管理",
        //     type: MenuPageType.PAGE,
        //     sort: 91,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "user",
        //     component: "settings/UserManagement",
        // }, {
        //     id: "1536652666153734144",
        //     pId: "1536652503813197824",
        //     actionId: "RoleMng",
        //     title: "角色管理",
        //     type: MenuPageType.PAGE,
        //     sort: 92,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "role",
        //     component: "settings/RoleManagement",
        // }, {
        //     id: "1536652853853032448",
        //     pId: "1536652503813197824",
        //     actionId: "MenuMng",
        //     title: "菜单管理",
        //     type: MenuPageType.PAGE,
        //     sort: 92,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "menu",
        //     component: "settings/MenuManagement",
        // }, {
        //     id: "1536652773624385536",
        //     pId: "1536652503813197824",
        //     actionId: "PermMng",
        //     title: "权限管理",
        //     type: MenuPageType.PAGE,
        //     sort: 94,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "permission",
        //     component: "settings/PermissionManagement",
        // }, {
        //     id: "1536652915467358208",
        //     pId: "1536652503813197824",
        //     actionId: "OrgMng",
        //     title: "组织机构管理",
        //     type: MenuPageType.PAGE,
        //     sort: 95,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "organization",
        //     component: "settings/OrganizationManagement",
        // },
        // {
        //     id: "1536653005456150528",
        //     pId: "1536652503813197824",
        //     actionId: "PwdMng",
        //     title: "密码修改",
        //     type: MenuPageType.PAGE,
        //     sort: 96,
        //     showInMenu: ShowInMenuType.SHOW,
        //     url: "password",
        //     component: "settings/PasswordManagement",
      }
    ],
  }, {
    id: "link",
    pId: "",
    actionId: "link",
    title: "外链",
    type: MenuPageType.LINK,
    sort: 97,
    showInMenu: ShowInMenuType.SHOW,
    url: "https://www.baidu.com",
  }, {
    id: "iframe",
    pId: "",
    actionId: "iframe",
    title: "IFrame",
    type: MenuPageType.IFRAME,
    sort: 98,
    showInMenu: ShowInMenuType.SHOW,
    url: "iframe",
    href: "http://10.0.0.10:6678/",
  }
] as ActionRecordRaw[];
