import type { ActionRecordRaw } from '@/types/action';

export const staticActions: ActionRecordRaw[] = createTree([
  {
    id: '1536647905518030848',
    actionId: 'menu',
    title: '示例菜单',
    type: MenuPageType.MENU,
    icon: 'i-mdi-format-list-text',
    sort: 1,
    showInMenu: ShowInMenuType.SHOW,
    url: 'page',
    children: [{
      id: 'page',
      pId: '1536647905518030848',
      actionId: 'page',
      title: '示例页面',
      type: MenuPageType.PAGE,
      sort: 11,
      showInMenu: ShowInMenuType.SHOW,
      url: '',
      component: 'pages/SamplePage.vue',
      meta: {
        title: '示例页面的示例标题',
        backEnable: true,
      },
    }],
  }, {
    id: '1536643442430447616',
    actionId: 'settings',
    title: '系统管理',
    type: MenuPageType.MENU,
    icon: 'i-mdi-cog-outline',
    sort: 9,
    showInMenu: ShowInMenuType.SHOW,
    url: 'settings',
    children: [
      {
        id: '1536652592875048960',
        pId: '1536643442430447616',
        actionId: 'UserMng',
        title: '用户管理',
        type: MenuPageType.PAGE,
        sort: 91,
        showInMenu: ShowInMenuType.SHOW,
        url: 'user',
        component: 'settings/user/UserManagement.vue',
      }, {
        id: '1536652666153734144',
        pId: '1536643442430447616',
        actionId: 'RoleMng',
        title: '角色管理',
        type: MenuPageType.PAGE,
        sort: 92,
        showInMenu: ShowInMenuType.SHOW,
        url: 'role',
        component: 'settings/role/RoleManagement.vue',
      }, {
        id: '1536652853853032448',
        pId: '1536643442430447616',
        actionId: 'ActionMng',
        title: '菜单管理',
        type: MenuPageType.PAGE,
        sort: 92,
        showInMenu: ShowInMenuType.SHOW,
        url: 'menu',
        component: 'settings/action/ActionManagement.vue',
      }, {
        id: '1536652773624385536',
        pId: '1536643442430447616',
        actionId: 'PermMng',
        title: '权限管理',
        type: MenuPageType.PAGE,
        sort: 94,
        showInMenu: ShowInMenuType.SHOW,
        url: 'permission',
        component: 'settings/perm/PermissionManagement.vue',
      }, {
        id: '1536652915467358208',
        pId: '1536643442430447616',
        actionId: 'OrgMng',
        title: '组织机构管理',
        type: MenuPageType.PAGE,
        sort: 95,
        showInMenu: ShowInMenuType.SHOW,
        url: 'organization',
        component: 'settings/org/OrganizationManagement.vue',
      },
      {
        id: '1536653005456150528',
        pId: '1536643442430447616',
        actionId: 'PwdMng',
        title: '密码修改',
        type: MenuPageType.PAGE,
        sort: 96,
        showInMenu: ShowInMenuType.SHOW,
        url: 'password',
        component: 'settings/pwd/PasswordManagement.vue',
      }, {
        id: '1536642212610183168',
        pId: '1536643442430447616',
        actionId: 'formDesigner',
        title: '表单设计器',
        type: MenuPageType.PAGE,
        sort: 2,
        showInMenu: ShowInMenuType.SHOW,
        url: 'form',
        component: 'form/FormDesigner.vue',
      },
    ],
  }, {
    id: 'link',
    actionId: 'link',
    title: '外链',
    type: MenuPageType.LINK,
    icon: 'i-mdi-link',
    sort: 7,
    showInMenu: ShowInMenuType.SHOW,
    url: 'link',
    href: 'https://www.baidu.com',
  }, {
    id: 'iframe',
    actionId: 'iframe',
    title: 'IFrame',
    type: MenuPageType.IFRAME,
    icon: 'i-mdi-image-filter-drama-outline',
    sort: 8,
    showInMenu: ShowInMenuType.SHOW,
    url: 'iframe',
    href: 'https://next.antdv.com/components/overview-cn',
  },
]);
