import type {ActionItem} from "@/types";

export const staticActions = [{
    id: "menu1",
    pId: "",
    menuId: "Menu1",
    title: "菜单1",
    type: 0,
    url: "",
    icon: "",
    component: "",
    sort: 1,
    showInMenu: "1",
    children: [{
        id: "menu1-1",
        pId: "menu1",
        menuId: "Menu11",
        title: "菜单1-1",
        type: 0,
        url: "",
        icon: "",
        component: "",
        sort: 11,
        showInMenu: "1",
        children: [{
            id: "menu1-1-1",
            pId: "menu1-1",
            menuId: "Menu111",
            title: "菜单1-1-1",
            type: 1,
            url: "",
            icon: "",
            component: "",
            sort: 111,
            showInMenu: "1",
            children: [{
                id: "menu1-1-1-1",
                pId: "menu1-1-1",
                menuId: "Menu1111",
                title: "菜单1-1-1-1",
                type: 1,
                url: "",
                icon: "",
                component: "",
                sort: 1111,
                showInMenu: "1",
            }],
        }, {
            id: "menu1-1-2",
            pId: "menu1-1",
            menuId: "Menu112",
            title: "菜单1-1-2",
            type: 1,
            url: "",
            icon: "",
            component: "",
            sort: 112,
            showInMenu: "1",
        }],
    }, {
        id: "menu1-2",
        pId: "menu1",
        menuId: "Menu12",
        title: "菜单1-2",
        type: 0,
        url: "",
        icon: "",
        component: "",
        sort: 12,
        showInMenu: "1",
        children: [{
            id: "menu1-2-1",
            pId: "menu1-2",
            menuId: "Menu121",
            title: "菜单1-2-1",
            type: 1,
            url: "",
            icon: "",
            component: "",
            sort: 121,
            showInMenu: "1",
        }, {
            id: "menu1-2-2",
            pId: "menu1-2",
            menuId: "Menu122",
            title: "菜单1-2-2",
            type: 1,
            url: "",
            icon: "",
            component: "",
            sort: 122,
            showInMenu: "1",
        }],
    }, {
        id: "menu1-3",
        pId: "menu1",
        menuId: "Menu13",
        title: "菜单1-3",
        type: 0,
        url: "",
        icon: "",
        component: "",
        sort: 13,
        showInMenu: "1",
    }],
}, {
    id: "1536643442430447616",
    pId: "",
    menuId: "SysMng",
    title: "系统管理",
    type: 0,
    url: "",
    // icon: "#icon-system-management",
    component: "",
    sort: 9,
    showInMenu: "1",
    children: [
        {
            id: "1536652592875048960",
            pId: "1536652503813197824",
            menuId: "UserMng",
            title: "用户管理",
            type: 1,
            url: "/user-management",
            icon: "",
            // component: "settings/UserManagement",
            sort: 91,
            showInMenu: "1",
        },
        {
            id: "1536652666153734144",
            pId: "1536652503813197824",
            menuId: "RoleMng",
            title: "角色管理",
            type: 1,
            url: "/role-management",
            icon: "",
            // component: "settings/RoleManagement",
            sort: 92,
            showInMenu: "1",
        },
        {
            id: "1536652853853032448",
            pId: "1536652503813197824",
            menuId: "MenuMng",
            title: "菜单管理",
            type: 1,
            url: "/menu-management",
            icon: "",
            // component: "settings/MenuManagement",
            sort: 92,
            showInMenu: "1",
        },
        {
            id: "1536652773624385536",
            pId: "1536652503813197824",
            menuId: "PermMng",
            title: "权限管理",
            type: 1,
            url: "/permission-management",
            icon: "",
            // component: "settings/PermissionManagement",
            sort: 94,
            showInMenu: "1",
        },
        {
            id: "1536652915467358208",
            pId: "1536652503813197824",
            menuId: "OrgMng",
            title: "组织机构管理",
            type: 1,
            url: "/organization-management",
            icon: "",
            // component: "settings/OrganizationManagement",
            sort: 95,
            showInMenu: "1",
        },
        {
            id: "1536653005456150528",
            pId: "1536652503813197824",
            menuId: "PwdMng",
            title: "密码修改",
            type: 1,
            url: "/password-management",
            icon: "",
            // component: "settings/PasswordManagement",
            sort: 96,
            showInMenu: "1",
        }
    ],
}] as ActionItem[];
